global = [
    { key = "Slash", action = "Search" },
    { key = "Semicolon", action = "Command" },
    { key = "Semicolon", shift = true, action = "Command" },
    { key = "T", ctrl = true, action = "SetSetting", args = ["THEME_FOLLOW_SYSTEM", "false"], chain = true },
    { key = "T", ctrl = true, action = "ToggleSetting", args = ["THEME_DARK"] },
    { key = "T", ctrl = true, shift = true, action = "ToggleSetting", args = ["THREAD_REPLIES_IN_MAIN_TIMELINE"] },
    { key = "S", ctrl = true, action = "ToggleSetting", args = ["RENDER_SCALE", "1.8", "1.0"] },
    { key = "U", ctrl = true, action = "ToggleSetting", args = ["SORT_BY_UNREAD"], destinations = ["Inbox"] },
    { key = "L", ctrl = true, action = "ToggleSetting", args = ["BURY_LOW_PRIORITY"], destinations = ["Inbox"] },
    { key = "F", ctrl = true, action = "ToggleSetting", args = ["PIN_FAVORITES"], destinations = ["Inbox"] },
    { key = "H", ctrl = true, action = "ToggleSetting", args = ["VIEW_HIDDEN_EVENTS"], destinations = ["Conversation", "ConversationThread"] },
    { key = "K", ctrl = true, action = "ToggleSetting", args = ["MINIMAL_MODE"] },
    { key = "F", ctrl = true, action = "ToggleSetting", args = ["PREFERRED_MESSAGE_FORMAT", "MARKDOWN", "HTML", "PLAIN"], destinations = ["Conversation", "ConversationThread"] },
    { key = "F", ctrl = true, shift = true, action = "ToggleSetting", args = ["FORMATTED_COMPOSER_PREVIEW"], destinations = ["Conversation", "ConversationThread"] },
    { key = "X", ctrl = true, shift = true, action = "Exit" },
    { key = "R", ctrl = true, action = "RecreateWindow" },
    { key = "R", ctrl = true, shift = true, action = "RecreateUi" },
]
appMessage = [
    { key = "Escape", action = "ClearAppMessages" },
    { key = "Enter", action = "ConfirmActionAppMessage" },
]
inbox = [
    { key = "One", ctrl = true, action = "ToggleAccountExclusivelySelected", args = ["1"] },
    { key = "Two", ctrl = true, action = "ToggleAccountExclusivelySelected", args = ["2"] },
    { key = "Three", ctrl = true, action = "ToggleAccountExclusivelySelected", args = ["3"] },
    { key = "Four", ctrl = true, action = "ToggleAccountExclusivelySelected", args = ["4"] },
    { key = "Five", ctrl = true, action = "ToggleAccountExclusivelySelected", args = ["5"] },
    { key = "Six", ctrl = true, action = "ToggleAccountExclusivelySelected", args = ["6"] },
    { key = "Seven", ctrl = true, action = "ToggleAccountExclusivelySelected", args = ["7"] },
    { key = "Eight", ctrl = true, action = "ToggleAccountExclusivelySelected", args = ["8"] },
    { key = "Nine", ctrl = true, action = "ToggleAccountExclusivelySelected", args = ["9"] },
    { key = "One", ctrl = true, shift = true, action = "ToggleAccountSelected", args = ["1"] },
    { key = "Two", ctrl = true, shift = true, action = "ToggleAccountSelected", args = ["2"] },
    { key = "Three", ctrl = true, shift = true, action = "ToggleAccountSelected", args = ["3"] },
    { key = "Four", ctrl = true, shift = true, action = "ToggleAccountSelected", args = ["4"] },
    { key = "Five", ctrl = true, shift = true, action = "ToggleAccountSelected", args = ["5"] },
    { key = "Six", ctrl = true, shift = true, action = "ToggleAccountSelected", args = ["6"] },
    { key = "Seven", ctrl = true, shift = true, action = "ToggleAccountSelected", args = ["7"] },
    { key = "Eight", ctrl = true, shift = true, action = "ToggleAccountSelected", args = ["8"] },
    { key = "Nine", ctrl = true, shift = true, action = "ToggleAccountSelected", args = ["9"] },
    { key = "H", action = "NavigateSpaceRelative", args = ["-1"] },
    { key = "I", action = "NavigateSpaceRelative", args = ["1"] },
    { key = "Zero", action = "SelectSpace", args = ["0"] },
    { key = "Equals", shift = true, action = "SelectSpaceIfNotHidden", args = ["p:notif"] },
    { key = "Equals", shift = true, action = "SelectSpace", args = ["p:unread"] },
    { key = "Equals", shift = true, action = "SelectSpace", args = ["p:notif"] },
]
room = [
    { key = "M", ctrl = true, action = "MarkRoomRead", destinations = ["Inbox"] },
    { key = "R", alt = true, action = "ClearEventCache" },
]
conversation = [
    { key = "G", shift = true, action = "JumpToBottom", chain = true },
    { key = "U", action = "JumpToFullyRead" },
    { key = "U", shift = true, action = "JumpToOwnReadReceipt" },
    { key = "I", action = "FocusComposer" },
    { key = "P", action = "ComposerPasteAttachment" },
    { key = "P", action = "ComposerPasteText" },
    { key = "I", ctrl = true, action = "ComposeMessage" },
    { key = "V", ctrl = true, action = "ComposerPasteAttachment" },
    { key = "N", ctrl = true, action = "ComposeNotice" },
    { key = "E", ctrl = true, shift = true, action = "ComposeEmote" },
    { key = "M", ctrl = true, shift = true, action = "MarkTimelineReadPrivate", chain = true },
    { key = "M", ctrl = true, shift = true, action = "MarkTimelineFullyRead", chain = true },
    { key = "F", alt = true, action = "MarkTimelineRead", chain = true },
    { key = "F", alt = true, action = "MarkTimelineFullyRead", chain = true },
    { key = "M", ctrl = true, action = "MarkTimelineRead", chain = true },
    { key = "M", ctrl = true, action = "MarkTimelineFullyRead" },
    { key = "Enter", action = "ComposerSuggestionApplySelected" },
    { key = "Enter", action = "ComposerSend" },
    { key = "Enter", ctrl = true, action = "ComposerSend" },
    { key = "Enter", shift = true, action = "ComposerInsertAtCursor", args = ["\n"] },
    { key = "Escape", action = "HideComposerIfEmpty" },
    { key = "Escape", shift = true, action = "ClearComposer" },
    { key = "Tab", action = "ComposerSuggestionFocusNext" },
    { key = "Tab", shift = true, action = "ComposerSuggestionFocusPrevious" },
]
event = [
    { key = "M", action = "MarkEventRead", chain = true },
    { key = "M", action = "MarkEventFullyRead", chain = true },
    { key = "R", action = "ComposeReply" },
    { key = "C", action = "ComposeReaction" },
    { key = "J", action = "ComposeEdit" },
    { key = "Y", action = "CopyContent" },
    { key = "Y", shift = true, action = "CopyEventSource" },
    { key = "Y", ctrl = true, action = "CopyEventId" },
    { key = "Y", ctrl = true, shift = true, action = "CopyFormattedBody" },
    { key = "Y", alt = true, shift = true, action = "CopyMxc" },
    { key = "B", action = "OpenContentLinks" },
    { key = "B", ctrl = true, action = "CopyContentLink" },
    { key = "D", ctrl = true, action = "Redact" },
    { key = "Delete", action = "Redact" },
    { key = "Backspace", action = "Redact" },
    { key = "Enter", action = "DownloadFileAndOpen" },
    { key = "O", action = "DownloadFileAndOpen" },
    { key = "One", ctrl = true, action = "ToggleReactionIndex", args = ["0"] },
    { key = "Two", ctrl = true, action = "ToggleReactionIndex", args = ["1"] },
    { key = "Three", ctrl = true, action = "ToggleReactionIndex", args = ["2"] },
    { key = "Four", ctrl = true, action = "ToggleReactionIndex", args = ["3"] },
    { key = "Five", ctrl = true, action = "ToggleReactionIndex", args = ["4"] },
    { key = "Six", ctrl = true, action = "ToggleReactionIndex", args = ["5"] },
    { key = "V", action = "ToggleDetails" },
]
user = []
navigation = [
    { key = "I", shift = true, action = "NavigateCurrent", args = ["InboxConversationSplit"], notDestinations = ["InboxConversationSplit"] },
    { key = "I", shift = true, action = "NavigateCurrent", args = ["inbox"], notDestinations = ["InboxConversationSplit"] },
    { key = "I", shift = true, ctrl = true, action = "NavigateInNewWindow", args = ["InboxConversationSplit"] },
    { key = "A", shift = true, action = "NavigateCurrent", args = ["accounts"] },
    { key = "A", shift = true, ctrl = true, action = "NavigateInNewWindow", args = ["accounts"] },
    { key = "S", shift = true, action = "NavigateCurrent", args = ["settings"] },
    { key = "S", shift = true, ctrl = true, action = "NavigateInNewWindow", args = ["settings"] },
    { key = "Slash", shift = true, action = "NavigateAuto", args = ["roomDetails"], destinations = ["Conversation", "ConversationThread"] },
    { key = "L", action = "NavigateAuto", args = ["members"], destinations = ["Conversation", "ConversationThread"] },
    { key = "L", ctrl = true, action = "NavigateAuto", args = ["reactions"], destinations = ["Conversation", "ConversationThread"] },
    { key = "L", shift = true, ctrl = true, action = "NavigateAuto", args = ["readReceipts"], destinations = ["Conversation", "ConversationThread"] },
    { key = "U", ctrl = true, action = "NavigateAuto", args = ["user"], destinations = ["Conversation", "ConversationThread", "RoomMembers", "MessageReactions", "MessageReadReceipts"] },
    { key = "T", shift = true, action = "NavigateAuto", args = ["thread"], destinations = ["Conversation", "ConversationThread"] },
    { key = "X", action = "CloseWindowUnlessLast" },
    { key = "F", alt = true, action = "CloseWindowUnlessLast", destinations = ["Conversation"] },
]
navigationItem = [
    { key = "Enter", action = "NavigateCurrent" },
    { key = "O", action = "NavigateInNewWindow" },
]
copyAble = [
    { key = "Y", alt = true, action = "CopyUserId" },
    { key = "Y", action = "CopyPlaintext" },
    { key = "Y", action = "CopyUserId" },
    { key = "Y", action = "CopyMxcUrl" },
]
focus = [
    { key = "A", action = "OpenContextMenu" },
    { key = "Enter", ctrl = true, action = "OpenContextMenu" },
    { key = "DirectionUp", action = "FocusUp" },
    { key = "DirectionDown", action = "FocusDown" },
    { key = "DirectionLeft", action = "FocusLeft" },
    { key = "DirectionRight", action = "FocusRight" },
    { key = "E", action = "FocusUp" },
    { key = "N", action = "FocusDown" },
    { key = "H", shift = true, action = "FocusVisibleListTop" },
    { key = "H", shift = true, action = "FocusTop" },
    { key = "M", shift = true, action = "FocusCenter" },
    { key = "L", shift = true, action = "FocusVisibleListBottom" },
    { key = "L", shift = true, action = "FocusBottom" },
    { key = "Escape", ctrl = true, action = "FocusParent" },
    { key = "Enter", action = "FocusEnterContainer" },
    { key = "MoveHome", action = "FocusTop" },
    { key = "MoveEnd", action = "FocusBottom" },
    { key = "O", ctrl = true, action = "FocusNextSplit" },
    { key = "G", action = "FocusByRole", args = ["LIST_ITEM"], chain = true },
    { key = "G", action = "FocusVisibleListStart", chain = true },
    { key = "G", shift = true, action = "FocusByRole", args = ["LIST_ITEM"], chain = true },
    { key = "G", shift = true, action = "FocusVisibleListBottom", chain = true },
]
list = [
    { key = "G", action = "ScrollToStart", chain = true },
    { key = "G", shift = true, action = "ScrollToBottom", chain = true },
]
split = [
    { key = "Q", ctrl = true, action = "Unsplit" },
    { key = "L", action = "Unsplit" },
    { key = "X", action = "Unsplit" },
]
